name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write

    steps:
      # This checks out the new tag, not the master branch. E.g. 'refs/tags/v26.2.12.0'
      - name: Check out the repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: "Create version file"
        shell: bash
        run: |
          printf -- '{"version": "%s"}' "${{github.ref_name}}" > mpvacious/version.json

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          branch: master
          commit_message: Update version file
          commit_user_name: GitHub Actions
          commit_user_email: noreply@github.com
          commit_author: GitHub <noreply@github.com>

      - name: "Create zip"
        shell: bash
        run: |
          make BRANCH=HEAD VERSION="${{github.ref_name}}"

      - name: "Create release"
        uses: softprops/action-gh-release@v2
        with:
          prerelease: false
          generate_release_notes: true
          append_body: true
          body_path: .github/RELEASE/release-boilerplate.md
          name: "mpvacious ${{github.ref_name}}"
          files: |
            .github/RELEASE/*.zip
            .github/RELEASE/*.conf
